### ISSUE TITLE
Aborted in WebContainer

### ISSUE THREAD

**Issue by d3lm** [electric-sql/pglite#2]
I am trying to run this in WebContainer and now that #1 was merged and released I am seeing the following error:

```
RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (file:///home/projects/node-oqtitn/node_modules/@electric-sql/pglite/dist/chunk-RM7SEAOI.js:412:15)
    at _abort (file:///home/projects/node-oqtitn/node_modules/@electric-sql/pglite/dist/chunk-RM7SEAOI.js:5626:7)
    at wasm://wasm/02d347d2:wasm-function[123]:0x77e6
    at wasm://wasm/02d347d2:wasm-function[6809]:0x6ac11a
    at wasm://wasm/02d347d2:wasm-function[4366]:0x437a87
    at wasm://wasm/02d347d2:wasm-function[14076]:0x9a2381
    at wasm://wasm/02d347d2:wasm-function[15480]:0x9de758
```

But only if there's a db folder. If you remove the folder then it works fine.

Any idea? I think it'd be nice to have a debug build as well where `-sASSERTIONS` is enabled. This could maybe be published under a specific `debug` tag?

**Comment by samwillis** [comment]
Hey @d3lm,

I've published a debug build with `-s ASSERTIONS=1` although I'm unsure is it's giving us any more detailed errors.
https://www.npmjs.com/package/@electric-sql/pglite/v/0.0.1-debug.2

There is also the `ASSERTIONS=2` and `SAFE_HEAP=1` options we can try.

**Comment by d3lm** [comment]
Thanks!

That's strange, cause it's still not giving more info and prints the same error 🤔

**Comment by vBuravlev** [comment]
Confirm. I couldn't run PG lite in any of the options. This repository is 100% erroneous code.

**Comment by Yaromey** [comment]
> Confirm. I couldn't run PG lite in any of the options. This repository is 100% erroneous code.

Same here. On Windows machine. Do you also use Windows?

**Comment by samwillis** [comment]
> Same here. On Windows machine. Do you also use Windows?

Hey @Yaromey, there's a bug on Windows #34, should be fixed this week!
